/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package api.sources;

import org.gradle.api.Project;
import org.gradle.testkit.runner.GradleRunner;

public class App {
    public String getGreeting() {
    	Project p;
    	GradleRunner r;
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
